name: raxvor
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  # ----------- UI -------------
  cupertino_icons: ^1.0.8

  # --------- Functionality -----------
  agora_rtc_engine: ^6.5.3
  image_picker: ^1.2.0
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.4
  supabase_flutter: ^2.10.3
  #firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_database: ^12.0.3

  permission_handler: ^11.0.0
  cloud_firestore: ^6.0.3
  firebase_messaging: ^16.0.3
  http: ^1.5.0
  intl: ^0.20.2
#  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/

